### PR TITLE
Fix / add absolute path to TCLSH ...

### PR DESCRIPTION
**Pull request by louiic**

### CODE REVIEW

**Comment by rovinski** [comment]
This change does not work if the required version of `tclsh` is not installed at the default location, e.g. if `/bin/tclsh` version is 8.4 but `/usr/local/tclsh` is 8.6. This script requires tcl 8.5+.

Why is this an issue? `tclsh` should be in `$PATH` by default if it's located in `/bin`.

**Comment by louiic** [comment]
Austin,

If the user do “module load calibre”, the tclsh got picked up from Calibre path.

So … if that is the case, we need to figure out how to pick tclsh from the path…

Louii

**Comment by tajayi** [comment]
I agree with Austin. My guess is that the calibre version of tclsh should work anyway. If the script requires as specific version of tcl then maybe we can update to `tclsh8.5` or `tclsh8.6`

Infact, for portability, the first line should be `#!/usr/bin/env sh`.

**Comment by rovinski** [comment]
@louiic local environment issues shouldn't be solved in the repository. You could edit `$PATH` manually as a hack, or you could make a module do specifically load `tclsh`, or you could modify the calibre module to append to `$PATH` rather than prepend.

**Pull request closed without merging**
