### PR TITLE
[design/black-parrot] Moving signals in the black-parrot design to output ports at the toplevel.

### PR DESCRIPTION
**Pull request by stdavids**
In order to properly simulate this design, the testbench needs access to `cmt_trace_stage_reg`, `cmt_trace_result`, and `cmt_trace_exc`. This PR takes those 3 signals and pushes them out the toplevel module so the testbench can use them during simulations.

### CODE REVIEW

**Comment by rovinski** [comment]
@stdavids can't the testbench access these wires using the instance name, e.g. `multi_top.cmt_trace_stage_reg`? Moving these signals to outputs will create over 500 I/O pins at the block level.

**Comment by stdavids** [comment]
In RTL that works, however, I believe that after synthesis we will lose those signal names so we lose our ability to simulate after synthesis. Is there any way to set an attribute on those wires to prevent name changes? Something like a dont_touch might work?

**Comment by rovinski** [comment]
That's an interesting question; I'm not sure. It would take some effort to find out how to do that without drastically altering the QoR. Is there a reason why we need to update this in the repo instead of in a local copy? I might be missing some context.

**Comment by stdavids** [comment]
The main idea was to set up a testbench to do some form of design verification. Currently, there is no real way to do any sort of functional verification of this specific black-parrot design without these signals, so after synthesis or place-and-route we can't do any sort of meaningful netlist simulation.

So the additional pins cause the design to fail PnR? This is increasing the number of pins from ~1200 to ~1700, is there any rule of thumb for the number of pins that we can have?

**Comment by rovinski** [comment]
I haven't run PnR on this PR, so I don't know if it would fail due to becoming pin-constrained (The CI failure is unrelated to this PR). It should be easy to increase the area to fit pins as required (we still only support pin placements on 1 horizontal layer / 1 vertical layer right now).

The main concern is that we are monitoring the QoR for our designs, and this change would cause a major hiccup in the metrics for this design. For RTL bug fixes, I totally understand sucking it up and dealing with the new RTL. But for changes to make verification easier, I'm not really sure about that at this moment. Formal verification isn't a part of our flow right now, although our team may be doing some experiments internally.

So I guess the question comes back to: does this change need to affect everyone who uses this design? If you're trying to run formal verification, can you just make the changes locally for whatever experiment you're running?

If you can find yosys options that would give you the naming that you need without significantly impacting QoR, I'd be much more willing to accept a PR along those lines.

**Comment by tspyrou** [comment]
I think this needs to go in even if there is a qor hiccup since we need to show a clear chain of custody from a clean rtl which passes formal verification.

**Comment by tspyrou** [comment]
Would this affect the IO ring or is it internal pins?

**Comment by rovinski** [comment]
@tspyrou this would be a 40% increase in I/O pin count. The reason for this change is because flattening in yosys is removing the signal names. There are likely other, better solutions that wouldn't impact QoR but this one will definitely work (at a likely significant QoR cost.

**Comment by rovinski** [comment]
@stdavids is this still an open issue?

**Pull request closed without merging**
