### PR TITLE
Update padLefMacro.py

### PR DESCRIPTION
**Pull request by ax3ghazy**
- Generalized to 2D (padding top & bottom sides).
- Fixed some regexes that had problems with whitespaces.
- args are optional and default to 0.

### CODE REVIEW

**Comment by ax3ghazy** [comment]
May be more appropriate to merge than the #25.

**Comment by rovinski** [comment]
Hi @ax3ghazy,

What is the purpose for adding vertical padding for cells? This would create multi-height standard cells and cause unnecessary difficulty in cell placement. Horizontal padding is only used as a stand-in to ease pin access while padding is being implemented in OpenDB.

**Comment by ax3ghazy** [comment]
Hi @rovinski,

I haven't used it on standard cells but rather on macros, which have arbitrary sizes, to "simulate" a halo around them to ease their pin access (since usually pins are placed there all around on all sides) making sure the detailed placer doesn't place standard cells too close.

**Comment by rovinski** [comment]
Setting halos around macros is already setting in IP_global.cfg. Let me know if this is not what you're looking for.

https://github.com/The-OpenROAD-Project/OpenROAD-flow/blob/caa249f51a5f0dcec491cebb29eab5f0d7c39d55/flow/platforms/nangate45/IP_global.cfg#L14-L17

**Comment by rovinski** [comment]
This was inadvertently closed due to a renaming of the 'develop' branch to 'openroad'. If these changes are still required, you can reopen a PR to the 'openroad' branch.

**Comment by ax3ghazy** [comment]
> Setting halos around macros is already an option in IP_global.cfg. Let me know if this is not what you're looking for.
> 
> https://github.com/The-OpenROAD-Project/OpenROAD-flow/blob/caa249f51a5f0dcec491cebb29eab5f0d7c39d55/flow/platforms/nangate45/IP_global.cfg#L14-L17

Yea, It does exactly what I need. Anyway, some of the regexes weren't parsing the LEF files I had properly, so I just fixed that. I also thought it would be a useful addition to have vertical padding for whatever reason and wanted to share my modifications in case they're relevant.

Thanks anyway!

**Pull request closed without merging**
